# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecohubserver

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ecohubcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_84f9591b18594c30a0950fc549fad64a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d76f73dadfb8421f8bad3ca1fb60681b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ecohubcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84f9591b18594c30a0950fc549fad64a }}/server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecohubserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6b3b2bc83c844c92942be2b3eda30435 }}
        images: 'ecohubcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84f9591b18594c30a0950fc549fad64a }}/server:${{ github.sha }}'